#!/bin/sh
# download music from youtube, soundcloud, etc

set -e
function main
{
	# Get command line options
	OPTERR=1
	local save_location='~/Music'			# default Music location
	local artist=""
	local album=""

	while getopts ":hl:a:A:d:" opt; do
	    case $opt in
	        h)
	            	print_help
	            	exit 0
	            	;;
		l)
			link=$OPTARG
			;;
		a)
			album=$OPTARG
			;;
		A)
			artist=$OPTARG
			;;
	        d)
	        	save_location=$OPTARG
	            	;;
	        *)
	            	exit_fail "Illegal parameter!"
	            	;;
	    esac
	done

	echo -e 'downloading file to	: ' $save_location
	download
	exit 0

}

function download {
	if [ -n "$artist" ] && [ -z "$album" ]
	then
		youtube-dl -i --extract-audio --audio-format best --add-metadata -o $save_location/"$artist/%(album)s/%(playlist_index)s-%(track)s.%(ext)s" $link
	elif [ -n "$album" ] && [ -z "$artist" ]
	then
		youtube-dl -i --extract-audio --audio-format best --add-metadata -o $save_location"/%(artist)s/$album/%(playlist_index)s-%(track)s.%(ext)s" $link
	elif [ -n "$album" ] && [ -n "$artist" ]
	then
		location=$save_location/$artist/$album
		youtube-dl -i --extract-audio --audio-format best --add-metadata -o $save_location"/$artist/$album/%(playlist_index)s-%(track)s.%(ext)s" $link
	else
		youtube-dl -i --extract-audio --audio-format best --add-metadata -o $save_location'/%(artist)s/%(album)s/%(playlist_index)s-%(track)s.%(ext)s' $link
	fi
}

function print_help
{
	echo
	echo "This script uses youtube-dl to download audio files from youtube/soundloud/bandcamp ... "
	echo "It will also save them automatically at a given location on following "
	echo "format: /given_dest/artist/album/track"
	echo
	echo "Usage:"
	echo
	echo "	$(basename "$0") [-h]  |  -l <url link to video/audio> [ -d <save location>"
	echo
	echo "Where:"
	echo
	echo "	-h	Display help and exit"
	echo "	-l 	url link"
	echo "	-A 	Artist"
	echo "	-a 	album"
	echo " 	-d	save location (default is /Music)"
	echo "	-a 	(optional) Album name"
	echo "	-A 	(optional) Artist name"
	echo
}

# Run script
main "$@"

# We should not end up here
exit 42
link=$1
