#!/bin/sh

xrandr --output DisplayPort-0 --off --output DisplayPort-1 --off --output HDMI-A-0 --mode 2560x1440 --pos 0x0 --rotate normal --output HDMI-A-1 --off --output DVI-D-0 --mode 1920x1080 --pos 2560x0 --rotate left
#xrandr --output HDMI-A-0 --auto --output DVI-D-0 --rotate left --auto --right-of HDMI-A-0
